### ISSUE TITLE
食谱推荐

### ISSUE THREAD

**Issue by syx11237744** [Alchuang22-dev/DEC_sustainable_diet_helper#104]
### 背景
我们计划实现一个后端接口，用于向用户推荐食谱。具体的推荐逻辑可以根据用户的偏好、饮食限制或历史记录进行定制。为了确保接口满足前端需求，需要明确前端会传递哪些参数，以及返回的结果格式。

### 接口初步设计
- **URL**: `/api/recipes/recommend`
- **方法**: POST 或 GET（需前端确认）

### 需前端确认的内容
1. **传递参数的具体内容和格式**
   - 偏好设置：例如用户喜欢的菜系或食物类型。
   - 饮食限制：如是否对某些成分过敏（无坚果、无乳糖等）。
   - 是否需要排序功能（如按热度或评分）。

2. **返回结果的字段需求及数据结构**
   - 必须返回哪些字段（如标题、描述、图片、热量等）。

### 完成标准
- [ ] 前端明确参数内容和返回格式。
- [ ] 接口开发完成并通过单元测试。
- [ ] 提供接口文档，供前端对接。
- [ ] 接口通过前后端联调，返回数据符合预期。

### 责任人
- 后端开发: @syx11237744
- 前端对接: @Alchuang22-dev

### 备注
如有其他需求，请在评论区补充。

**Comment by Alchuang22-dev** [comment]
> 目前前端实现的reference代表的内容存在于
> ..\DEC_sustainable_diet_helper\frontend\pagesMy\foodPreferences\foodPreferences.json

# 需要对接的接口

## 传递饮食偏好

+ 方法：POST（后端可决定是否拆分为DELETE）
+ 数据：
  + TYPE1：当用户更新references，前端发送"name_en"及method(add, delete)；
  + ` BODY: {"name": "high protein", "method": "delete"}`
  + TYPE2：前端发送完整的偏好信息及method
  + `BODY: {"name_en": "high protein","name_zh-Hans": "高蛋白饮食","nutrition_pos": "protein","nutrition_neg": "","food_pos": [],"food_neg": []}`
+ 返回结果：成功200

## 获取饮食偏好

+ 方法：GET`/userid`
+ 数据: （后端决定是否需要发送lang参数）
+ 返回结果：`[{"id":1,"name":"high protein"}{"id":2,"name":"low sugar"}]`



如对foodPreferences.json有疑问请联系。

**Comment by syx11237744** [comment]
> > 目前前端实现的reference代表的内容存在于
> > ..\DEC_sustainable_diet_helper\frontend\pagesMy\foodPreferences\foodPreferences.json
> 
> # 需要对接的接口
> ## 传递饮食偏好
> * 方法：POST（后端可决定是否拆分为DELETE）
> * 数据：
>   
>   * TYPE1：当用户更新references，前端发送"name_en"及method(add, delete)；
>   * ` BODY: {"name": "high protein", "method": "delete"}`
>   * TYPE2：前端发送完整的偏好信息及method
>   * `BODY: {"name_en": "high protein","name_zh-Hans": "高蛋白饮食","nutrition_pos": "protein","nutrition_neg": "","food_pos": [],"food_neg": []}`
> * 返回结果：成功200
> 
> ## 获取饮食偏好
> * 方法：GET`/userid`
> * 数据: （后端决定是否需要发送lang参数）
> * 返回结果：`[{"id":1,"name":"high protein"}{"id":2,"name":"low sugar"}]`
> 
> 如对foodPreferences.json有疑问请联系。

我认为这个部分可以新开一个issue，这个issue主要是对接食谱推荐的，我再开一个issue吧 @Alchuang22-dev

**Comment by Alchuang22-dev** [comment]
> Re: 我认为这个部分可以新开一个issue，这个issue主要是对接食谱推荐的，我再开一个issue吧 [[@Alchuang22-dev](https://github.com/Alchuang22-dev)](https://github.com/Alchuang22-dev)

## 关于饮食偏好

如上所述

## 关于饮食限制

前端尚未实现此功能

## 关于历史记录

我认为对于历史记录的分析似乎放在纯后端为宜，关于历史记录的删除、编辑，前端未来会提供方法。

如果后二者有进一步讨论的必要，可以单开issue @syx11237744

**Comment by syx11237744** [comment]
转移到另一个issue #112
